<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="An Icon Font Generated By IcoMoon.io">
    <title>Document</title>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Great+Vibes&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=PT+Serif&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../../font/font-awesome-4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="../../font/icomoon/style.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="../../style/scss/main.css">
    <link rel="stylesheet" href="../../style/scss/details.css ">
    <link rel="stylesheet" href="../../style/scss/media-query.css">
    <script src="../../js/jquery-3.4.0.js"></script>
</head>
<body>
<div class="page">
    <header>
        <div class="head">
            <div class="inform">
                <div class="container flex flex-center flex-space-between">
                    <div class="flex flex-center">
                        <span class="info-youremail-com icon">info@youremail.com</span>
                        <span class="border"></span>
                        <a class="my-phone icon" href="tel:+(56)123456546">+(56) 123 456 546</a>
                    </div>
                    <div class="flex flex-center">
                        <span class="border"></span>
                        <span class="my-account" id="my-account">My Account  </span>
                    </div>
                </div>
            </div>
            <div class="logo flex flex-center">
                <div class="container flex flex-center flex-space-between">
                    <div>
                        <a href="/" title="На главную"><img src="../../img/svg/Logo.svg" alt=""></a>
                    </div>
                    <div class="search-field">
                        <input type="text" placeholder="Inter Your Keyword. . .">
                        <div class="search-btn "><span></span></div>
                    </div>
                </div>
            </div>
            <nav class="flex flex-center flex-justify-center">
                <div class="container flex flex-center ">
                    <div class="subsection flex ">
                        <span>Home</span>
                        <span>Man</span>
                        <span>Women</span>
                        <span>Kids</span>
                        <span>Accoseriese</span>
                        <span>FeatureD</span>
                    </div>
                    <div class="social flex">
                        <a href="#"><span class="facebook-icon icon"></span></a>
                        <a href="#"><span class="twitter-icon icon"></span></a>
                        <a href="#"><span class="google-icon icon"></span></a>
                        <a href="#"><span class="pinterest-icon icon"></span></a>
                        <a href="#"><span class="skype-icon icon"></span></a>
                    </div>
                </div>
            </nav>
        </div>
        <div class="poster flex flex-center">
            <div>
                <span class="blog">Blog</span>
                <span class="blog-latest-news">LATEST NEWS</span>
                <div class="block-way">
                    <span class="way-to-section way">Home</span>
                    <span class="right-arrow icon"></span>
                    <span class="way-to-section section">News</span>
                </div>
            </div>
        </div>
    </header>
    <div class="section flex flex-justify-center">
        <? include_once(ROOT . '/application/views/' . $content_view); ?>
    </div>
    <div class="brands-bar flex flex-center">
        <div class="head"><span>OUR BRANDS</span></div>
        <div class="logotip-head flex flex-justify-center"><span></span></div>
        <div class="scroll-bar flex">
            <div class=" arrow flex flex-center">
                <span class="left-arrow icon flex flex-center"></span>
            </div>
            <div class="scroll-bar-in flex flex-center flex-justify-center">
                <div class="brand flex-justify-center flex flex-center"><img src="../../img/retrologo.jpg" alt="brand">
                </div>
                <div class="brand flex-justify-center flex flex-center"><img src="../../img/retrologo2.jpg" alt="brand">
                </div>
                <div class="brand flex-justify-center flex flex-center"><img src="../../img/retrologo3.jpg" alt="brand">
                </div>
                <div class="brand flex-justify-center flex flex-center"><img src="../../img/retrologo4.jpg" alt="brand">
                </div>
                <div class="brand flex-justify-center flex flex-center "><img src="../../img/retrologo5.jpg"
                                                                              alt="brand">
                </div>
                <div class="brand flex-justify-center flex flex-center"><img src="../../img/retrologo6.jpg" alt="brand">
                </div>
            </div>
            <div class=" arrow flex flex-center">
                <span class="right-arrow icon flex flex-center"></span>
            </div>
        </div>
    </div>
    <div class="box-to-subscribe flex-center flex flex-justify-center">
        <div class=" logotip  flex flex-center">
            <span class="logotip-left flex flex-center"></span>
        </div>
        <div class="subscribe">
            <div class="head flex flex-justify-center"><span>NEWSLETTER</span></div>
            <div class="logotip-head flex"><span></span></div>
            <div class="search-field flex flex-justify-center flex-center">
                <div>
                    <input type="text" placeholder="Enter your Email">
                    <input type="button" value="SUBSCRIBE" class="btn">
                </div>
            </div>
        </div>
        <div class=" logotip flex flex-center">
            <span class="logotip-right  flex flex-center"></span>
        </div>
    </div>
</div>
<footer>
    <div class="footer-info flex flex-center ">
        <div class="container">
            <div class="info-block flex ">
                <div class="info-list ul">
                    <span class="slider-span">MY ACCOUNT</span>
                    <ul class="ul">
                        <li><a href="#">My Orders</a></li>
                        <li><a href="#">My Credit Slips</a></li>
                        <li><a href="#">My Addresses</a></li>
                        <li><a href="#">My Personal Info</a></li>
                    </ul>
                </div>
                <div class="info-list ul">
                    <span class="slider-span">ORDERS</span>
                    <ul class="ul">
                        <li><a href="#">Payment Option</a></li>
                        <li><a href="#">Shipping</a></li>
                        <li><a href="#">Returns</a></li>
                        <li><a href="#">Delivery</a></li>
                    </ul>
                </div>
                <div class="info-list ul">
                    <span class="slider-span">INFORMATION</span>
                    <ul class="ul">
                        <li><a href="#">About us</a></li>
                        <li><a href="#">Delivery Information</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                        <li><a href="#">Custom Service</a></li>
                    </ul>
                </div>
                <div class="info-list  last-info-list ">
                    <span class="slider-span"> CONTACT US</span>
                    <ul>
                        <li><a href="#" class="address icon">68 Dohava Stress, Lorem isput Spusts. New York- United
                                State</a></li>
                        <li><a href="#" class="mail icon">info@youremail.com</a></li>
                        <li><a href="#" class="number icon">+1 (00) 42 868 666 888</a></li>
                    </ul>
                </div>
            </div>
            <div class="social-networks flex ">
                <div class="social flex flex-center">
                    <a href="#"><span class="facebook-icon icon"></span></a>
                    <a href="#"><span class="twitter-icon icon"></span></a>
                    <a href="#"><span class="google-icon icon"></span></a>
                    <a href="#"><span class="pinterest-icon icon"></span></a>
                    <a href="#"><span class="skype-icon icon"></span></a>
                </div>
                <div class="payment flex flex-center">
                    <a href="#"><img src="../../img/visa.jpg" alt=""></a>
                    <a href="#"><img src="../../img/master-card.jpeg" alt=""></a>
                    <a href="#"><img src="../../img/discover.jpg" alt=""></a>
                    <a href="#"><img src="../../img/paypal.jpg" alt=""></a>
                    <a href="#"><img src="../../img/American_Expres.svg" alt=""></a>
                </div>
            </div>
            <div id="swipe-up" class="icon flex-justify-center flex"></div>
        </div>
    </div>
    <div class="copyright flex flex-center flex-justify-center">
        <span>Copyright © 2016, <span>Theme_Express</span>  All Rights Reseved.</span>
    </div>
</footer>
<div id="authorization">
    <div class="box-auth">
        <span id="close">Close</span>
        <form class="form-signin">
            <h1>Авторизация</h1>
            <div class="form-group form ">
                <label for="email">Введите ваш email</label>
                <input type="email" name="email" id="email" class="form-control">
            </div>
            <div class="form-group form">
                <label for="password">Введите новаую цену продута</label>
                <input type="password" name="password" id="password" class="form-control">
            </div>
            <input type="submit" value="войти" name="submit" class="btn btn-success" style="margin-right: 20px">
            <a href="/registration/index"><input type="button" value="Рагеистрация" class="btn btn-danger"></a>
        </form>
    </div>
</div>
<script src="../../js/js.js"></script>
</body>
</html>